export default Object.freeze({
  HOMETAB: 'HomeTab',
  HOME: 'Home',
  CATEGORIESTAB: 'CategoriesTab',
  CATEGORIES: 'Categories',
  FEEDTAB: 'FeedTab',
  FEED: 'Feed',
  ACCOUNTTAB: 'AccountTab',
  ACCOUNT: 'Account',
  HELPTAB: 'HelpTab',
  HELP: 'Help',
  PRODUCTDETAILS: 'ProductDetails',
  CART: 'Cart',
  NOTIFICATION: 'Notification',
  CHECKOUT: 'Checkout',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  SEARCHED: 'Searched',
});
