export default Object.freeze({
  HOMETAB: 'HomeTab',
  HOME: 'Home',
  CATEGORIESTAB: 'CategoriesTab',
  CATEGORIES: 'Categories',
  FEEDTAB: 'FeedTab',
  FEED: 'Feed',
  ACCOUNTTAB: 'AccountTab',
  ACCOUNT: 'Account',
  HELPTAB: 'HelpTab',
  HELP: 'Help',
  PRODUCTDETAILS: 'ProductDetails',
  CART: 'Cart',
  CHECKOUT: 'Checkout',
  LOGIN: 'login',
  SIGNUP: 'Signup',
});
